<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_Country', 'master');

/**
 * Model_Base_Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property enum $continent
 * @property string $region
 * @property float $surfacearea
 * @property integer $indepyear
 * @property integer $population
 * @property float $lifeexpectancy
 * @property float $gnp
 * @property float $gnpold
 * @property string $localname
 * @property string $governmentform
 * @property string $headofstate
 * @property integer $capital
 * @property string $code2
 * @property Doctrine_Collection $City
 * @property Doctrine_Collection $CountryLanguage
 * 
 * @package    Doctrine
 * @subpackage 
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Model_Base_Country extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Country');
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('name', 'string', 52, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '52',
             ));
        $this->hasColumn('continent', 'enum', 13, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Asia',
              1 => 'Europe',
              2 => 'North America',
              3 => 'Africa',
              4 => 'Oceania',
              5 => 'Antarctica',
              6 => 'South America',
             ),
             'primary' => false,
             'default' => 'Asia',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '13',
             ));
        $this->hasColumn('region', 'string', 26, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '26',
             ));
        $this->hasColumn('surfacearea', 'float', 10, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('indepyear', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('population', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('lifeexpectancy', 'float', 3, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('gnp', 'float', 10, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('gnpold', 'float', 10, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('localname', 'string', 45, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('governmentform', 'string', 45, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
        $this->hasColumn('headofstate', 'string', 60, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('capital', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('code2', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_City as City', array(
             'local' => 'code',
             'foreign' => 'countrycode'));

        $this->hasMany('Model_CountryLanguage as CountryLanguage', array(
             'local' => 'code',
             'foreign' => 'countrycode'));
    }
}