<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="<?php echo $this->baseUrl(); ?>" /> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <link rel="stylesheet" media="screen" type="text/css" href="/css/main.css" />
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
</head>

<body>


<div>
    <div>    
        <?php echo $this->layout()->content; ?>
    </div>
</div>

</body>
</html>
