<?php

/**
 * Model_Crud
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Doctrine
 * @subpackage 
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Model_Crud extends Model_Base_Crud
{

}